version: '3.9'

services:
  mongo_db_prod:
    image: mongo:5
    container_name: mongo_db_monster_prod
    ports:
      - 27017:27017
    environment:
      - MONGODB_DATABASE=monster-db
    volumes:
      - mongomonsterprod:/data/configdb
      - mongomonsterprod:/data/db
    networks:
      - nestjs-network-prod

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - nestjs-network

networks:
  nestjs-network-prod:
    name: nestjs-network-prod
    driver: bridge

volumes:
  mongomonsterprod: {}
