version: '3.9'

services:
  mongo_db:
    image: mongo:5
    container_name: mongo_db_monster_test
    ports:
      - 27017:27017
    environment:
      - MONGODB_DATABASE=monster-db-test
    volumes:
      - mongomonstertest:/data/configdb
      - mongomonstertest:/data/db

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - nestjs-network

networks:
  nestjs-network:
    name: nestjs-network
    driver: bridge

volumes:
  mongomonstertest: {}
  redis:
    driver: local
